dynamics_learning_rate: 0.1
rewards_ln: false
rewards_n_hiddens: 3
rewards_learning_rate: 0.1
dones_ln: true
dones_n_hiddens: 3
dones_learning_rate: 0.1
dones_cutoff: 0.6
dataset_name: halfcheetah-medium-v2
eval_episodes: 5
eval_every: 100
eval_seed: 42
eval_steps: 30
tau: 0.005
gamma: 0.99
group: myenv_gru-halfcheetah-medium-v2
hidden_dim: 256
name: myenv_gru
noise_clip: 0.5
normalize_reward: false
normalize_states: false
num_epochs: 100
num_updates_on_epoch: 100
project: myenv_gru
train_seed: 0
time_steps: 5
max_steps: 1024
reload_chkpt: true
chkpt_dir: /tmp/chkpt/myenv_gru/halfcheetah/medium_v2
